### PR TITLE
only run config for installed desktops

### PR DESCRIPTION
**Pull request by DEvil0000**
the config for gnome will only get executed when gnome is installed. the same is true for xfce.

### CODE REVIEW

**Comment by DEvil0000** [comment]
CLA on a MIT licensed repo - you must be kidding. Thats quite a duplication and no need to double on that

**Comment by freemanjp** [comment]
@DEvil0000 thanks for the pull request. Sorry the Travis CI build wasn't working (they've discontinued their opensource plan and I've not migrated all my projects yet). This project is now building using GitHub Actions, unfortunately, this change is presently failing the build.

**Comment by DEvil0000** [comment]
@freemanjp sorry for the linter bug, fixed that one. From my point of view it should work now. I suspect the check in molecule being to simple now since I check for installed xfce package before I execute that part.
Do you have a elegant idea for overcoming this?

**Comment by freemanjp** [comment]
Hi @DEvil0000, sorry for the late reply (my day job isn't leaving much time to spend on opensource at the moment). I think the only option is to change the Molecule test (https://github.com/gantsign/ansible-role-default-web-browser/blob/master/molecule/default/converge.yml) to preinstall Gnome and Xfce before running the role. I would say pick the minimal install possible (to minimise the build time). Ideally, there'd be separate molecule scenarios (one for Gnome and one for Xfce), I have some other roles that do this (e.g. https://github.com/gantsign/ansible-role-intellij/blob/master/.github/workflows/ci.yml), but I'm not making that a requirement.

**Comment by freemanjp** [comment]
No longer required as support for the Xfce desktop has been dropped from this role.

**Pull request closed without merging**
